name: Daily weather email

on:
  schedule:
    - cron: '0 4/19 * * *'

  workflow_dispatch:


jobs:
  weather:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get data
        id: data
        run: |
          cd ${{ github.workspace }}
          ls
          sh ${{ github.workspace }}/dist/forecast.sh
      - name: Push to GitHub
        uses: endbug/add-and-commit@v7.2.1
        with:
          branch: master
          message: 'Daily Update weather image'


    outputs:
      short: ${{ steps.data.outputs.short }}
      long: ${{ steps.data.outputs.long }}

  hito:
    runs-on: ubuntu-latest

    steps:
      - name: Get hitokoto
        id: hitokoto
        run: |
          sentence=`curl https://api.uixsj.cn/hitokoto/get?code=json | jq '. ["content"]'`
          echo "::set-output name=hitokoto::${sentence}"

    outputs:
      hitokoto: ${{ steps.hitokoto.outputs.hitokoto }}


  issue:
    runs-on: ubuntu-latest
    needs: [weather,hito]

    steps:
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: 4
          body: |
            # 今日天气 :zap:
            ## 总结
            ${{ needs.weather.outputs.short }}
            ***
            ## 其他信息
            ${{ needs.weather.outputs.long }}
            ***
            ## 预报图
            ![Weather](https://raw.githubusercontent.com/Guleixibian2009/Guleixibian2009/master/dist/weather.png)
            ***
            ## 今天的一言
            ${{ needs.hito.outputs.hitokoto }}
            ***
            *这条评论由[GitHub Actions](https://Guleixibian2009/Guleixibian2009/actions/)自动化发出！*
