name: Daily weather email

on:
  schedule:
    - cron: '0 4/19 * * *'

  workflow_dispatch:


jobs:
  data:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get data
        id: data
        run: |
          cd ${{ github.workspace }}
          ls
          ${{ github.workspace }}/dist/forecast.sh
      - name: Push to GitHub
        uses: endbug/add-and-commit@v7.2.1
        with:
          branch: master
          message: 'Daily Update weather image'
      - name: Get hitokoto
        id: hito
        run: |
          sentence=`curl https://api.uixsj.cn/hitokoto/get?code=json | jq '. ["content"]'`
          echo "::set-output name=hito::${sentence}"

    outputs:
      short: ${{ steps.data.outputs.short }}
      long: ${{ steps.data.outputs.long }}
      hito: ${{ steps.hito.outputs.hito }}

  issue:
    runs-on: ubuntu-latest
    needs: data

    steps:
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: 4
          body: |
            # 今日天气 :zap:
            ## 总结
            ${{ needs.data.outputs.short }}
            ***
            ## 其他信息
            ${{ needs.data.outputs.long }}
            ***
            ## 预报图
            ![Weather](https://raw.githubusercontent.com/Guleixibian2009/Guleixibian2009/master/dist/weather.png)
            ***
            ## 今天的一言
            ${{ needs.data.outputs.hito }}
            ***
            *这条评论由[GitHub Actions](https://Guleixibian2009/Guleixibian2009/actions/)自动化发出！*
