name: Daily weather email

on:
  schedule:
    - cron: '0 4/23 * * *'

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      

